version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      nuget:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /third_party/xterm
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      xterm:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - "*"
