<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Pact.Core\Pact.Core.csproj" />
    <PackageReference Include="YamlDotNet" />
    <InternalsVisibleTo Include="Pact.Presentation.Tests" />
    <InternalsVisibleTo Include="Pact.Infrastructure.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="AgentControl\PactSkills\*.md" />
    <Content Include="Defaults\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\third_party\conpty\1.25.260303002\win10-x64\conpty.dll" Link="conpty\conpty.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\third_party\conpty\1.25.260303002\win10-x64\OpenConsole.exe" Link="conpty\OpenConsole.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
